deploy_env: dev
micro:
  server_name: "go.micro.srv.passport"
  server_version: "1.0.0"
  register_ttl: 30
  register_interval: 15
  registry: etcd
  registry_address:
    - "192.168.2.125:2379"
logger:
  level: "debug"
  filename: "app.log"
  max_size: 100
  max_backups: 10
  max_age: 7
  compress: false
tracer:
  addr: "192.168.2.125:6831"
stan:
  addrs:
    - "nats://192.168.2.125:4222"
  cluster_id: "test-cluster"
mysql:
  data_source: "root:123456@tcp(192.168.2.125:13306)/dm_passport"
redis:
  addr: "192.168.2.125:6379"
  password: "123456"
  db: 0
