deploy_env: dev
micro:
  server_name: "go.micro.web.dd"
  server_version: "1.0.0"
  register_ttl: 30
  register_interval: 15
  registry: etcd # 用于服务发现，向 etcd 注册本 service 的地址和名字
  registry_address:
    - "192.168.2.125:2379"
logger:
  level: "debug"
  filename: "app.log"
  max_size: 100
  max_backups: 10
  max_age: 7
  compress: false
tracer:
  addr: "192.168.2.125:6831"
