// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/proto/topic/ums.proto

package dmicro_topic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type L2A struct {
	Proto                int32    `protobuf:"varint,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Appid                int32    `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Platform             int32    `protobuf:"varint,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Cmd                  int32    `protobuf:"varint,6,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Seq                  int32    `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload              []byte   `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2A) Reset()         { *m = L2A{} }
func (m *L2A) String() string { return proto.CompactTextString(m) }
func (*L2A) ProtoMessage()    {}
func (*L2A) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de47eb76dac6f91, []int{0}
}

func (m *L2A) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2A.Unmarshal(m, b)
}
func (m *L2A) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2A.Marshal(b, m, deterministic)
}
func (m *L2A) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2A.Merge(m, src)
}
func (m *L2A) XXX_Size() int {
	return xxx_messageInfo_L2A.Size(m)
}
func (m *L2A) XXX_DiscardUnknown() {
	xxx_messageInfo_L2A.DiscardUnknown(m)
}

var xxx_messageInfo_L2A proto.InternalMessageInfo

func (m *L2A) GetProto() int32 {
	if m != nil {
		return m.Proto
	}
	return 0
}

func (m *L2A) GetAppid() int32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *L2A) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *L2A) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *L2A) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *L2A) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *L2A) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *L2A) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Req struct {
	Appid                int32    `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Platform             int32    `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Cmd                  int32    `protobuf:"varint,5,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Seq                  int32    `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	Body                 []byte   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de47eb76dac6f91, []int{1}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetAppid() int32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *Req) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Req) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *Req) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Req) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Req) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Req) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// umsg -> appserver
type IM struct {
	Appid                int32    `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Terminal             int32    `protobuf:"varint,3,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Cmd                  int32    `protobuf:"varint,5,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Seq                  int32    `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	Body                 []byte   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IM) Reset()         { *m = IM{} }
func (m *IM) String() string { return proto.CompactTextString(m) }
func (*IM) ProtoMessage()    {}
func (*IM) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de47eb76dac6f91, []int{2}
}

func (m *IM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IM.Unmarshal(m, b)
}
func (m *IM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IM.Marshal(b, m, deterministic)
}
func (m *IM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IM.Merge(m, src)
}
func (m *IM) XXX_Size() int {
	return xxx_messageInfo_IM.Size(m)
}
func (m *IM) XXX_DiscardUnknown() {
	xxx_messageInfo_IM.DiscardUnknown(m)
}

var xxx_messageInfo_IM proto.InternalMessageInfo

func (m *IM) GetAppid() int32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *IM) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *IM) GetTerminal() int32 {
	if m != nil {
		return m.Terminal
	}
	return 0
}

func (m *IM) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *IM) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *IM) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *IM) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*L2A)(nil), "dmicro.topic.L2A")
	proto.RegisterType((*Req)(nil), "dmicro.topic.Req")
	proto.RegisterType((*IM)(nil), "dmicro.topic.IM")
}

func init() { proto.RegisterFile("common/proto/topic/ums.proto", fileDescriptor_8de47eb76dac6f91) }

var fileDescriptor_8de47eb76dac6f91 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x31, 0x6a, 0xc3, 0x30,
	0x18, 0x46, 0x91, 0x25, 0x3b, 0xe1, 0xc7, 0x43, 0x11, 0x1d, 0x44, 0xe9, 0x60, 0x3c, 0x79, 0x8a,
	0xa1, 0x3d, 0x41, 0xc7, 0x42, 0xbb, 0xe8, 0x06, 0x8a, 0xa5, 0x82, 0xc0, 0x8a, 0x64, 0x5b, 0x19,
	0x7c, 0x8f, 0xf6, 0x20, 0xbd, 0x61, 0xd1, 0x6f, 0xdc, 0x0c, 0x71, 0x87, 0x42, 0xb6, 0xef, 0x3d,
	0x09, 0xf1, 0x40, 0xf0, 0xd8, 0x79, 0xe7, 0xfc, 0xa9, 0x0d, 0xa3, 0x8f, 0xbe, 0x8d, 0x3e, 0xd8,
	0xae, 0x3d, 0xbb, 0xe9, 0x80, 0xcc, 0x4b, 0xed, 0x6c, 0x37, 0xfa, 0x03, 0xfa, 0xfa, 0x9b, 0x00,
	0x7d, 0x7b, 0x7a, 0xe1, 0xf7, 0x90, 0xe3, 0xb1, 0x20, 0x15, 0x69, 0x72, 0xb9, 0x40, 0xb2, 0x2a,
	0x04, 0xab, 0x45, 0xb6, 0x58, 0x04, 0x7e, 0x07, 0xf4, 0x6c, 0xb5, 0xa0, 0x15, 0x69, 0x98, 0x4c,
	0x93, 0x3f, 0xc0, 0x3e, 0xf4, 0x2a, 0x7e, 0xf8, 0xd1, 0x09, 0x86, 0x57, 0x7f, 0x99, 0x73, 0x60,
	0x71, 0x0e, 0x46, 0xe4, 0xe8, 0x71, 0xa7, 0x17, 0x3a, 0xa7, 0x45, 0x81, 0x2a, 0xcd, 0x64, 0x26,
	0x33, 0x88, 0xdd, 0x62, 0x26, 0x33, 0x70, 0x01, 0xbb, 0xa0, 0xe6, 0xde, 0x2b, 0x2d, 0xf6, 0x15,
	0x69, 0x4a, 0xb9, 0x62, 0xfd, 0x45, 0x80, 0x4a, 0x33, 0x5c, 0xea, 0xc8, 0x46, 0x5d, 0xb6, 0x5d,
	0x47, 0xff, 0xa8, 0x63, 0xd7, 0x75, 0xf9, 0x55, 0x5d, 0x71, 0xa9, 0xe3, 0xc0, 0x8e, 0x5e, 0xcf,
	0x18, 0x5c, 0x4a, 0xdc, 0xf5, 0x27, 0x81, 0xec, 0xf5, 0xfd, 0x3f, 0x59, 0xd1, 0x8c, 0xce, 0x9e,
	0x54, 0xbf, 0x66, 0xad, 0x7c, 0xcb, 0xac, 0x63, 0x81, 0x7f, 0xf9, 0xfc, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x04, 0x3a, 0x9e, 0xa0, 0x17, 0x02, 0x00, 0x00,
}
